var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/service-areas/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5eb6dc77._.js")
R.c("server/chunks/ssr/_35b03dc2._.js")
R.c("server/chunks/ssr/_d896cbcc._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43463263._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__98fececb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_service-areas_[slug]_page_actions_14d49db2.js")
R.m(40196)
module.exports=R.m(40196).exports
